# Generated by Django 3.0.6 on 2020-08-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
