# Generated by Django 3.0.6 on 2020-08-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0002_auto_20200815_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='key_words',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Configrations.Tag'),
        ),
    ]
