# Generated by Django 3.0.6 on 2020-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0004_auto_20200815_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catogory',
        ),
        migrations.AddField(
            model_name='post',
            name='catogory',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
