# Generated by Django 3.0.6 on 2020-08-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configrations', '0005_auto_20200815_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
